spring.application.name=BackendUtccSOS
spring.datasource.url=jdbc:mysql://localhost:3306/campussos?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ให้ Spring Boot ช่วยสร้างและอัปเดตตารางอัตโนมัติ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true